version: '3.4'

services:
  deident:
    image: deident
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m uvicorn reverse-proxy.api:app --host 0.0.0.0 --port 8081"]
    ports:
      - 8081:8081
      - 5678:5678
