version: '3.4'

services:
  data-service:  
    env_file:
      - .env.dev
      - .env.secret.dev
      - .env
    image: data
    build:
      context: ./data
      dockerfile: ./Dockerfile
    volumes:
      - $PWD/app:/data/app
    environment:
      - APP_MESSAGE=Hello debugger
    networks: 
      - medi-net
    ports:
      - 8082:8081

  ui-service:
    image: ui
    build:
      context: ./ui
      dockerfile: ./Dockerfile
    volumes:
      - $PWD/app:/ui/app
    networks: 
      - medi-net
    ports:
      - "8081:8081"
  ai-service:
    image: ai
    build:
      context: ./ai
      dockerfile: ./Dockerfile
    volumes:
      - $PWD/app:/ai/app
    networks: 
      - medi-net
    ports:
      - 8083:8081
networks:
  medi-net:
    driver: bridge