version: '3.4'

services:
  ui-service:
    env_file:
      - .env.dev
      - .env.secret.dev
      - .env
    image: ui
    build:
      context: ./ui
      dockerfile: ./Dockerfile.dev
    volumes:
      - $PWD/ui/app:/ui/app
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --listen 0.0.0.0:3003 -m uvicorn app.api:app --host 0.0.0.0 --port 8081 --reload"]
    environment:
      - APP_MESSAGE=Hello debugger
    networks: 
      medi-net:
        aliases:
          - deident-ui-service
    ports:
      - "8081:8081"
      - "3003:3003"

  data-service:  
    env_file:
      - .env.dev
      - .env.secret.dev
      - .env
    image: data
    build:
      context: ./data
      dockerfile: ./Dockerfile.dev
    volumes:
      - $PWD/data/app:/data/app
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --listen 0.0.0.0:3002 -m uvicorn app.api:app --host 0.0.0.0 --port 8082 --reload"]
    environment:
      - APP_MESSAGE=Hello debugger
    networks: 
      medi-net:
        aliases:
          - deident-data-service
    ports:
      - "8082:8082"
      - "3002:3002"

  ai-service:
    image: ai
    env_file:
      - .env.dev
      - .env.secret.dev
    build:
      context: ./ai
      dockerfile: ./Dockerfile.dev
    volumes:
      - $PWD/ai/app:/ai/app
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --listen 0.0.0.0:5678 -m uvicorn app.api:app --host 0.0.0.0 --port 8083 --reload"]
    environment:
      - APP_MESSAGE=Hello debugger
    networks: 
      medi-net:
        aliases:
          - deident-ai-service
    ports:
      - "8083:8083"
      - "5678:5678"
networks:
  medi-net:
    driver: bridge
    name: medi-net
    
    

