version: '3.4'

volumes:
  deidentdata:


services:
  web-service:
    env_file:
      - ${PWD}/.env.dev
      - ${PWD}/.env.secret.dev
      - ${PWD}/.env
    image: web
    build:
      context: ${PWD}/web
      dockerfile: ${PWD}/web/Dockerfile.dev
    volumes:
      - deidentdata:/code/web/volume
    command:
      [
        "sh",
        "-c",
        "pip install debugpy -t /tmp && python /tmp/debugpy --listen 0.0.0.0:3003 -m uvicorn app.api:app --host 0.0.0.0 --port 8081 --reload"
      ]
    environment:
      - APP_MESSAGE=Hello debugger
    networks:
      medi-net:
        aliases:
          - deID-web-service
    ports:
      - "8081:8081"
      - "3003:3003"

  data-service:
    env_file:
      - ${PWD}/.env.dev
      - ${PWD}/.env.secret.dev
      - ${PWD}/.env
    image: data
    build:
      context: ${PWD}/data
      dockerfile: ${PWD}/data/Dockerfile.dev
    volumes:
      - deidentdata:/code/data/volume
    command:
      [
        "sh",
        "-c",
        "pip install debugpy -t /tmp && python /tmp/debugpy --listen 0.0.0.0:3002 -m uvicorn app.api:app --host 0.0.0.0 --port 8082 --reload"
      ]
    environment:
      - APP_MESSAGE=Hello debugger
    networks:
      medi-net:
        aliases:
          - deID-data-service
    ports:
      - "8082:8082"
      - "3002:3002"

  ai-service:
    image: ai
    env_file:
      - ${PWD}/.env.dev
      - ${PWD}/.env.secret.dev
      - ${PWD}/.env
    build:
      context: ${PWD}/ai
      dockerfile: ${PWD}/ai/Dockerfile.dev
    volumes:
      - deidentdata:/code/ai/volume
    command:
      [
        "sh",
        "-c",
        "pip install debugpy -t /tmp && python /tmp/debugpy --listen 0.0.0.0:5678 -m uvicorn app.api:app --host 0.0.0.0 --port 8083 --reload"
      ]
    environment:
      - APP_MESSAGE=Hello debugger
    networks:
      medi-net:
        aliases:
          - deID-ai-service
    ports:
      - "8083:8083"
      - "5678:5678"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.3
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - deidentdata:/usr/share/elasticsearch/data
    networks:
      medi-net:
        aliases:
          - elasticsearch
  kibana:
    image: docker.elastic.co/kibana/kibana:8.4.3
    environment:
      ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"

    ports:
      - "5601:5601"
    networks:
      medi-net:
        aliases:
          - kibana
networks:
  medi-net:
    driver: bridge
    name: medi-net
