# # For more information, please refer to https://aka.ms/vscode-docker-python
FROM python:3.9-slim-buster

# EXPOSE 8083

# Keeps Python from generating .pyc files in the container
ENV PYTHONDONTWRITEBYTECODE=1

# Turns off buffering for easier container logging
ENV PYTHONUNBUFFERED=1

WORKDIR /code/ai

COPY ./requirements.txt /code/ai/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /code/ai/requirements.txt
# # -------------------------------------------------------------------------#
# # DEV MODE
# # -------------------------------------------------------------------------#

# # TODO: make a prod docker file
# RUN pip install https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.5.1/en_core_sci_sm-0.5.1.tar.gz 

# # -------------------------------------------------------------------------#
# # END DEV MODE
# # -------------------------------------------------------------------------#


# # -------------------------------------------------------------------------#
# # SpaCy DeID init
# # -------------------------------------------------------------------------#

# WORKDIR /code/ai/app/services/spacy/deid
# COPY ./app/services/spacy/ /code/ai/app/services/spacy/
# RUN ls -la
# RUN pip install -r requirements.txt
# # download the prebuilt vectors for the other components
# RUN python -m spacy project assets
# # download the pretrained model NOTE: this should be commented out after our first training 
# # see project.yml
# RUN python -m spacy project run download
# RUN python -m spacy project run all

# WORKDIR /code/ai
# # -------------------------------------------------------------------------#
# # END SpaCy DeID init
# # -------------------------------------------------------------------------#

COPY . .

CMD ["uvicorn", "app.api:app", "--host", "0.0.0.0", "--port", "8083", "--log-level", "debug"]