version: '3.4'
services:
  ai:
    image: ai
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - $PWD/app:/app
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m uvicorn app.api:app --host 0.0.0.0 --port 8083 --reload"]
    environment:
      - APP_MESSAGE=Hello debugger
    ports:
      - 8083:8083
      - 5678:5678
    # networks:
    #   - medi-net