version: '3.4'

volumes:
  deidentdata:
services:
  ai-service:
    image: ai
    env_file:
      - ${PWD:-.}/.env.dev
      - ${PWD:-.}/.env.secret.dev
      - ${PWD:-.}/.env
    build:
      context: ${PWD:-.}/ai
      dockerfile: ./Dockerfile.dev
    volumes:
      - deidentdata:/code/ai/volume
    command:
      [
        "sh",
        "-c",
        "pip install debugpy -t /tmp && python /tmp/debugpy --listen 0.0.0.0:5678 -m uvicorn app.api:app --host 0.0.0.0 --port 8083 --reload"
      ]
    environment:
      - APP_MESSAGE=Hello debugger
    networks:
      medi-net:
        aliases:
          - deID-ai-service
    ports:
      - "8083:8083"
      - "5678:5678"
