version: '3.4'
services:
  ui-service:
    image: ui
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - $PWD/app:/ui/app
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:3003 -m uvicorn app.api:app --host 0.0.0.0 --port 8081 --reload"]
    environment:
      - APP_MESSAGE=Hello debugger
    networks: 
      - medi-net
    ports:
      - 8081:8081
      - 3003:3003
