# # For more information, please refer to https://aka.ms/vscode-docker-python
FROM python:3.9-slim-buster

# EXPOSE 8081

# Keeps Python from generating .pyc files in the container
ENV PYTHONDONTWRITEBYTECODE=1

# Turns off buffering for easier container logging
ENV PYTHONUNBUFFERED=1

WORKDIR /code/web

COPY ./requirements.txt /code/web/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /code/web/requirements.txt
# # -------------------------------------------------------------------------#
# # DEV MODE
# # -------------------------------------------------------------------------#

# # TODO: handle this with an environment variable and a flag you savage
# # -------------------------------------------------------------------------#
# # END DEV MODE
# # -------------------------------------------------------------------------#

COPY . .

CMD ["uvicorn", "app.api:app", "--host", "0.0.0.0", "--port", "8081", "--log-level", "debug"]