version: '3.4'

volumes:
  deidentdata:


services:
  web-service:
    env_file:
      - ../.env.dev
      - ../.env.secret.dev
      - ../.env
    image: web
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    volumes:
      - deidentdata:/code/web/volume
    command:
      [
        "sh",
        "-c",
        "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:3003 -m uvicorn app.api:app --host 0.0.0.0 --port 8081 --reload"
      ]
    environment:
      - APP_MESSAGE=Hello debugger
    # networks: 
    #   medi-net:
    #     aliases:
    #       - web-service
    ports:
      - "8081:8081"
      - "3003:3003"

# networks: 
#   medi-net:
#     external: true
#     name: medi-net
