version: '3.4'

volumes:
  deidentdata:


services:
  web-service:
    env_file:
      - ${PWD:-.}/.env.dev
      - ${PWD:-.}/.env.secret.dev
      - ${PWD:-.}/.env
    image: web
    build:
      context: ${PWD:-.}/web
      dockerfile: ./Dockerfile.dev
    volumes:
      - deidentdata:/code/web/volume
    command:
      [
        "sh",
        "-c",
        "pip install debugpy -t /tmp && python /tmp/debugpy --listen 0.0.0.0:3003 -m uvicorn app.api:app --host 0.0.0.0 --port 8081 --reload"
      ]
    environment:
      - APP_MESSAGE=Hello debugger
    networks:
      medi-net:
        aliases:
          - deID-web-service
    ports:
      - "8081:8081"
      - "3003:3003"
